[package]

name = "cli"
version = "0.0.1"
authors = ["Evan Meagher <evan.meagher@gmail.com>"]
description = "A practical library for building command-line programs in Rust"
repository = "https://github.com/evnm/cli.rs"
license = "MIT"
readme = "README.md"

[dependencies]
getopts = "0.1.4"
